### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character

### ISSUE THREAD

**Issue by w4po** [evilpan/jni_helper#10]
Hello,

I've encountered an error:
```
Traceback (most recent call last):
  File "D:\jni_helper\extract_jni.py", line 326, in <module>
    parse_apk(args.apk, args.workers, outfile=args.outfile)
  File "D:\jni_helper\extract_jni.py", line 316, in parse_apk
    json.dump(output, f, indent=2, ensure_ascii=False)
  File "C:\Users\USERNAME\.pyenv\pyenv-win\versions\3.12.1\Lib\json\__init__.py", line 180, in dump
    fp.write(chunk)
  File "C:\Users\USERNAME\.pyenv\pyenv-win\versions\3.12.1\Lib\encodings\cp1256.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u039f' in position 18: character maps to <undefined>
```

I've fixed it by specifying the encoding in the `open` call in line 315: `with open(outfile, "w", encoding="utf-8") as f:`

https://github.com/evilpan/jni_helper/blob/70572696fd114cbdc5a41c5859bb2e9fed0fc7b6/extract_jni.py#L315

**Comment by evilpan** [comment]
Thanks for your report! Already fixed in latest commit.
