### ISSUE TITLE
elftools.common.exceptions.ELFParseError: String Table not found

### ISSUE THREAD

**Issue by pb222xd** [evilpan/jni_helper#12]
```python
[21:19:05] Parsing [hidden]\jni_helper\[hidden].apk with 20     extract_jni.py:253
           workers ...
[21:19:06] Found 36 DEX files.                                                                        extract_jni.py:255
[21:19:19] Parse classes.dex (11222728 bytes), found 4785 classes.                                    extract_jni.py:282
[21:19:22] Parse classes10.dex (9895140 bytes), found 5549 classes.                                   extract_jni.py:282
           Parse classes11.dex (9189568 bytes), found 4899 classes.                                   extract_jni.py:282
           Parse classes12.dex (8030728 bytes), found 4512 classes.                                   extract_jni.py:282
           Parse classes13.dex (3856404 bytes), found 4481 classes.                                   extract_jni.py:282
[21:19:38] Parse classes14.dex (10461900 bytes), found 12782 classes.                                 extract_jni.py:282
[21:19:47] Parse classes15.dex (10437384 bytes), found 17193 classes.                                 extract_jni.py:282
           Parse classes16.dex (11691516 bytes), found 14644 classes.                                 extract_jni.py:282
           Parse classes17.dex (10922692 bytes), found 12181 classes.                                 extract_jni.py:282
           Parse classes18.dex (11506292 bytes), found 11239 classes.                                 extract_jni.py:282
           Parse classes19.dex (10178044 bytes), found 10611 classes.                                 extract_jni.py:282
           Parse classes2.dex (9289836 bytes), found 6536 classes.                                    extract_jni.py:282
           Parse classes20.dex (10428876 bytes), found 10826 classes.                                 extract_jni.py:282
           Parse classes21.dex (10276988 bytes), found 9496 classes.                                  extract_jni.py:282
           Parse classes22.dex (10660148 bytes), found 9835 classes.                                  extract_jni.py:282
           Parse classes23.dex (9506120 bytes), found 9137 classes.                                   extract_jni.py:282
           Parse classes24.dex (10846476 bytes), found 10863 classes.                                 extract_jni.py:282
           Parse classes25.dex (10619136 bytes), found 9435 classes.                                  extract_jni.py:282
           Parse classes26.dex (9696588 bytes), found 9379 classes.                                   extract_jni.py:282
           Parse classes27.dex (10178304 bytes), found 11825 classes.                                 extract_jni.py:282
           Parse classes28.dex (11235044 bytes), found 8736 classes.                                  extract_jni.py:282
           Parse classes29.dex (9319492 bytes), found 19111 classes.                                  extract_jni.py:282
           Parse classes3.dex (10668500 bytes), found 6201 classes.                                   extract_jni.py:282
           Parse classes30.dex (9294640 bytes), found 9724 classes.                                   extract_jni.py:282
           Parse classes31.dex (9614960 bytes), found 8398 classes.                                   extract_jni.py:282
           Parse classes32.dex (8523224 bytes), found 7859 classes.                                   extract_jni.py:282
           Parse classes33.dex (9586492 bytes), found 8604 classes.                                   extract_jni.py:282
[21:19:48] Parse classes34.dex (8415168 bytes), found 8054 classes.                                   extract_jni.py:282
           Parse classes35.dex (7691472 bytes), found 7400 classes.                                   extract_jni.py:282
           Parse classes36.dex (6543784 bytes), found 6526 classes.                                   extract_jni.py:282
           Parse classes4.dex (9378540 bytes), found 5505 classes.                                    extract_jni.py:282
           Parse classes5.dex (10062444 bytes), found 8290 classes.                                   extract_jni.py:282
           Parse classes6.dex (12067864 bytes), found 8468 classes.                                   extract_jni.py:282
           Parse classes7.dex (10059692 bytes), found 7340 classes.                                   extract_jni.py:282
           Parse classes8.dex (10458996 bytes), found 5640 classes.                                   extract_jni.py:282
           Parse classes9.dex (9229448 bytes), found 5315 classes.                                    extract_jni.py:282
Analyzing Dex... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:41
           Analyzed 321379 classes, cost: 0:00:41.110476                                              extract_jni.py:291
[21:19:49] Found 175 so files.                                                                        extract_jni.py:295
           Found 3 JNI symbols in lib/arm64-v8a/[hidden].so.                                       extract_jni.py:300
           Found 1 JNI symbols in lib/arm64-v8a/[hidden].so.                                   extract_jni.py:300
           Found 2 JNI symbols in lib/arm64-v8a/[hidden].so.                                    extract_jni.py:300
           Found 6 JNI symbols in lib/arm64-v8a/[hidden].so.                                          extract_jni.py:300
           Found 2 JNI symbols in lib/arm64-v8a/[hidden].so.                                       extract_jni.py:300
           Found 11 JNI symbols in lib/arm64-v8a/[hidden].so.                                 extract_jni.py:300
           Found 10 JNI symbols in lib/arm64-v8a/[hidden].so.                                     extract_jni.py:300
           Found 137 JNI symbols in lib/arm64-v8a/[hidden].so.                                       extract_jni.py:300
           Found 1 JNI symbols in lib/arm64-v8a/[hidden].so.                                    extract_jni.py:300
           Found 8 JNI symbols in lib/arm64-v8a/[hidden].so.                                      extract_jni.py:300
           Found 1 JNI symbols in lib/arm64-v8a/[hidden].so.                                extract_jni.py:300
[21:19:50] Found 49 JNI symbols in lib/arm64-v8a/[hidden].so.                                     extract_jni.py:300

Traceback (most recent call last):
  File "[hidden]\jni_helper\extract_jni.py", line 334, in <module>
    parse_apk(args.apk, args.workers, outfile=args.outfile)
  File "[hidden]\jni_helper\extract_jni.py", line 297, in parse_apk
    possible_symbols = parse_so_sync(soFile)
                       ^^^^^^^^^^^^^^^^^^^^^
  File "[hidden]\jni_helper\extract_jni.py", line 223, in parse_so_sync
    funcs = get_exported_functions(sofile.data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[hidden]\jni_helper\extract_jni.py", line 197, in get_exported_functions
    symbol_tables = [
                    ^
  File "[hidden]\jni_helper\extract_jni.py", line 197, in <listcomp>
    symbol_tables = [
                    ^
  File "[hidden]\jni_helper\venv\Lib\site-packages\elftools\elf\elffile.py", line 174, in iter_sections
    section = self.get_section(i)
              ^^^^^^^^^^^^^^^^^^^
  File "[hidden]\jni_helper\venv\Lib\site-packages\elftools\elf\elffile.py", line 141, in get_section
    return self._make_section(section_header)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[hidden]\jni_helper\venv\Lib\site-packages\elftools\elf\elffile.py", line 637, in _make_section
    name = self._get_section_name(section_header)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[hidden]\jni_helper\venv\Lib\site-packages\elftools\elf\elffile.py", line 629, in _get_section_name
    raise ELFParseError("String Table not found")
elftools.common.exceptions.ELFParseError: String Table not found
```

**Comment by evilpan** [comment]
Maybe it's caused by the obfuscated ELF, Could you attach the target APK file, or just the obfuscated so library so that I can test with it?

**Comment by evilpan** [comment]
Anyway, I tried to add exception handling logic in the latest commit, please check if it fix your issue.

**Comment by pb222xd** [comment]
> Maybe it's caused by the obfuscated ELF, Could you attach the target APK file, or just the obfuscated so library so that I can test with it?

Sorry, still raise `elftools.common.exceptions.ELFParseError: String Table not found`

**Comment by pb222xd** [comment]
> Maybe it's caused by the obfuscated ELF, Could you attach the target APK file, or just the obfuscated so library so that I can test with it?

Yeah, [hidden]

**Comment by evilpan** [comment]
Hi @pb222xd, I've test with your apk and it works fine:
```sh
$ ./extract_jni.py base.apk -o base.json
[11:29:44] Found 36 DEX files. 
...
[11:30:05] skip library lib/arm64-v8a/libMiniAppCore.so: String Table not found
...
[11:30:06] skip library lib/arm64-v8a/libuvjni.so: String Table not found
```

It correctly skips the problematic ELF, are you sure that you're using the latest code(i.e. the master branch)?

**Comment by pb222xd** [comment]
Sorry, I retried today and found that it’s working fine now. Thank you!
