### ISSUE TITLE
JNI Helper for IDA can't use in IDA PRO 7.5 SP3

### ISSUE THREAD

**Issue by rama291041610** [evilpan/jni_helper#2]
Some api have changed.

https://www.hex-rays.com/products/ida/support/ida74_idapython_no_bc695_porting_guide.shtml

**Comment by xmhwws** [comment]
IDA PRO 7.5 SP3、python3.9，一运行IDA就是如下提示：
```
[+] plugin run
D:\crack\PC\IDA\plugins\jni_helper3.py: Function requires a database
Traceback (most recent call last):
  File "D:\crack\PC\IDA\python\3\ida_idaapi.py", line 616, in IDAPython_ExecScript
    exec(code, g)
  File "D:/crack/PC/IDA/plugins/jni_helper3.py", line 105, in <module>
    main()
  File "D:/crack/PC/IDA/plugins/jni_helper3.py", line 76, in main
    if not is_jni_header_loaded():
  File "D:/crack/PC/IDA/plugins/jni_helper3.py", line 34, in is_jni_header_loaded
    ret = idc.parse_decl('JNIEnv *env', idc.PT_SILENT)
  File "D:\crack\PC\IDA\python\3\idc.py", line 5095, in parse_decl
    return ida_typeinf.idc_parse_decl(None, inputtype, flags)
  File "D:\crack\PC\IDA\python\3\ida_typeinf.py", line 9463, in idc_parse_decl
    return _ida_typeinf.idc_parse_decl(*args)
RuntimeError: Function requires a database
```

可能问题并未解决

**Comment by evilpan** [comment]
Should be fixed by [8dac48](https://github.com/evilpan/jni_helper/commit/8dac481df80feb05beca9364311ba76b029e039c). Now we could load IDA plugin by putting jni_helper in `$IDA_HOME/plugins` or by just click `Alt + F7` (File -> Script File) without installing.

**Comment by xmhwws** [comment]
拿demo的例子测试了，没有问题，正常运行
